version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 9mREsvXDs9Gk89Ef
      PGDATA: /var/lib/postgresql/data/pgdata

  adminer:
    image: adminer
    restart: always
    ports:
      - 5432:5432
      - 8080:8080
    volumes:
      - ./custom/mount:/var/lib/postgresql/data