version: '3.1'

services:
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef
      - PGDATA=/var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data

