version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 123qwerty


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080